apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secrets-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://{{ .Values.vaultName | default "kv-temporal" }}.vault.azure.net/
      serviceAccountRef:
        name: eso-sa
        namespace: {{ .Values.namespace }}
