apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureClientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azureTenantId | quote }}
