apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-sa-identity
  namespace: temporal-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secrets-store
    kind: ClusterSecretStore
  target:
    name: eso-sa-identity
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: eso-client-id
    - secretKey: tenantId
      remoteRef:
        key: eso-tenant-id
