replicaCount: 1

image:
  repository: acrtemporal49e78cc7.azurecr.io/multiagent-orchestrator
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

secretName: temporal-env-vars
mountPath: /etc/certs