apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secrets-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-temporal.vault.azure.net/
      serviceAccountRef:
        name: eso-sa
        namespace: temporal-workers