apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-worker-config
  namespace: temporal-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secrets-store
    kind: ClusterSecretStore
  target:
    name: temporal-env-vars
    creationPolicy: Owner
  data:
    - secretKey: TEMPORAL_ADDRESS
      remoteRef:
        key: temporal-address
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openai-api-key
    - secretKey: client.crt
      remoteRef:
        key: client-crt
    - secretKey: client.key
      remoteRef:
        key: client-key
