apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-worker-config
  namespace: temporal-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secrets-store
    kind: ClusterSecretStore
  target:
    name: temporal-env-vars
    creationPolicy: Owner
  data:
    - secretKey: TEMPORAL_NAMESPACE
      remoteRef:
        key: temporal-namespace
    - secretKey: TEMPORAL_API_KEY
      remoteRef:
        key: temporal-api-key
