apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-orchestrator
  labels:
    app: multiagent-orchestrator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multiagent-orchestrator
  template:
    metadata:
      labels:
        app: multiagent-orchestrator
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TEMPORAL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: TEMPORAL_ADDRESS
            - name: TEMPORAL_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: TEMPORAL_NAMESPACE
          volumeMounts:
            - name: certs
              mountPath: {{ .Values.mountPath }}
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.secretName }}
            items:
              - key: client.crt
                path: client.crt
              - key: client.key
                path: client.key
