apiVersion: v1
kind: Service
metadata:
  name: temporal-worker
  labels:
    app: temporal-worker
spec:
  selector:
    app: temporal-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Adjust if your worker exposes an API
