apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.tenantId | quote }}
