apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.annotations.azure.workload.identity/client-id | quote }}
    azure.workload.identity/tenant-id: {{ .Values.serviceAccount.annotations.azure.workload.identity/tenant-id | quote }}
